apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: application
type: Opaque
stringData:
  DBHOST: mysqldemo1.mysql.database.azure.com
  DBUSERNAME: azureuser
  DBPASSWORD: admin@123
  DBNAME: appdb
  DBDIALECT: mysql
