apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: application
type: Opaque
stringData:
  MYSQL_HOST: your-mysql-server.mysql.database.azure.com
  MYSQL_USER: mysqladmin
  MYSQL_PASSWORD: yourpassword
  MYSQL_DB: appdb
