apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: app
type: Opaque
stringData:
  MYSQL_HOST: mysqldemo1.mysql.database.azure.com
  MYSQL_USER: azureuser
  MYSQL_PASSWORD: admin@123
  MYSQL_DB: appdb
